---
user_id: ""  #find username on page: https://www.spotify.com/us/account/overview/
client_id: "" #create new app on page: https://developer.spotify.com/dashboard/applications Set redirect URIs to: http://localhost:9090
client_sec: "" #secret should be given to you when your app is created
